package com.example.placely.data.entity

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Defines the structure for storing Reminders (Tests, Interviews, Deadlines).
 * The table name will be 'reminders'.
 */
@Entity(tableName = "reminders")
data class ReminderEntity(
    // The primary key for this table, auto-generated by Room
    @PrimaryKey(autoGenerate = true)
    val id: Int = 0,

    val title: String,
    val description: String?,
    // Date and time stored as a Long (milliseconds since epoch) for easy sorting and comparison
    val dateTime: Long,
    // e.g., "Online Test", "Interview", "Resume Deadline"
    val type: String,
    // How long before the event the notification should trigger (in milliseconds)
    val notificationAlert: Long
)
